modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/Oreberries-Replanted"
license="MIT"

[[mods]]
modId="oreberriesreplanted"
version="${file.jarVersion}"
displayName="Oreberries Replanted"
displayURL="https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted"
authors="Mrbysco, ShyNieke"
description='''
Are you tired of your ores generating in rock? Do you want to grow your ore? Well, you no longer have to hope! Now you can grow ores in the form of berries
'''
credits="Lanse505 for the idea of crushing oreberries into juice that evaporates into nuggets"
[[dependencies.oreberriesreplanted]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
[[dependencies.oreberriesreplanted]]
modId="jei"
mandatory=false
versionRange="[9.5.0.132,)"
ordering="NONE"
side="BOTH"